### ISSUE TITLE
Can't revive

### ISSUE THREAD

**Issue by HySand** [Cycro54/Revive_Me#9]
Kill works, but can't revive. Holding use button make the progress screen flash.
I tested Canary, Player Trade and Swing Through Grass
Here's my modpack
[CirCube Fantasy.zip](https://github.com/Cycro54/Revive_Me/files/14270101/CirCube.Fantasy.zip)

**Comment by Cycro54** [comment]
Thank you for telling me, I'll fix it as soon as I'm able!

**Comment by Cycro54** [comment]
That was such a huge bug I am surprised it took so long for someone to report it XD
It should be fixed in the latest versions, please tell me if anything else goes wrong.

https://legacy.curseforge.com/minecraft/mc-mods/revive-me/files/5122290

**Comment by HySand** [comment]
> That was such a huge bug I am surprised it took so long for someone to report it XD It should be fixed in the latest versions, please tell me if anything else goes wrong.
> 
> https://legacy.curseforge.com/minecraft/mc-mods/revive-me/files/5122290

Still can't revive in my server.Then I tested it in a LAN server, only host can revive.
